version: '3.2'
services:
  app:
    build:
      context: ./
      dockerfile: ./app.dockerfile
    working_dir: /var/www
#    command: "php artisan key:generate & composer install & php artisan migrate --seed & php artisan cache:clear"
    volumes:
      -  ./:/var/www/
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    ports:
      - 80:80
      - 443:443
  # The Database
  database:
    image: mysql:5.6
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - "MYSQL_DATABASE=learndocker"
    - "MYSQL_USER=root"
    - "MYSQL_PASSWORD=abc123"
    - "MYSQL_ROOT_PASSWORD=abc123"
    ports:
    - "33061:3306"

volumes:
  dbdata: